server:
  port: 56600
  #servlet:
  #  context-path: /kytms-business

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kytms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  application:
    name: jwxt-zuuls #指定服务名

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath:com/kytms/*/mapper/*.xml


redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  jedis:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  timeout: 50000


ftp:
  host: 192.168.5.210
  port: 22
  username: root
  password: root


#首页显示的微服务名默认为：机器主机名:应用名称:应用端口，
#也就是：${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:56698/eureka/,http://localhost:56699/eureka/
  instance:
    prefer-ip-address: true
    instance-id: myZuuls #在注册中心页面显示的微服务名



ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

zuul:
  routes:
    jwxt-teacher:
      path: /teacher/**  #访问的路径
      service-id: jwxt-business   #访问的服务
    jwxt-learner:
      path: /student/**
      service-id: jwxt-student
    ignored-services: '*'
  #ignored-patterns: /**/findOne/**   #忽略带有findOne的请求（就不能再访问带有findOne的请求）
  #prefix: /api     #访问路径的前缀，需要多加一层的/api
#  ratelimit:            #3秒内访问次数不允许超过2次，并且这2次请求要小于5秒
#    enabled: true       #开启限流开关
#    behind-proxy: true  #开启限流代理
#    default-policy:
#      limit: 2          #单元时间内置允许访问2次
#      quota: 5          #单元时间内每个请求不得超过5秒
#      refresh-interval: 3   #单元时间 3秒
#      type:
#        - user
#        - origin
#        - url
#      policies:
#        jwxt-student:   #特定服务
#          limit: 4      #单元时间内置允许访问4次
#          quota: 5      #单元时间内每个请求不得超过5秒
#          refresh-interval: 3   #单元时间3


down:
  service: jwxt-student


